#!/bin/bash
PROGARGS=();
PROGNAME="g++";
DIRNAME=`dirname "$0"`;
## The algorithm is identicaly between gcc and g++, therefore  ##
## a change to one unsually requires a change to the other!    ##
for ARG in "$@"; do
	if [ "${NEXT}" == "-arch" ]; then
		if [ "${ARG}" == "i386" ]; then
			PROGARGS+=("-m32");
		elif [ "${ARG}" == "x86_64" ]; then
			PROGARGS+=("-m64");
		else
			PROGARGS+=("${NEXT}" "$ARG");
		fi
		unset NEXT
	elif [ "${ARG}" == "-arch" ]; then
		NEXT="${ARG}";
	else
		PROGARGS+=("${ARG}");
	fi
done
exec "${DIRNAME}/${PROGNAME}" "${PROGARGS[@]}";