#!/bin/bash
PROGARGS=();
DIRNAME=`dirname "$0"`;
BASENAME=`basename "$0"`;
PROGNAME="${DIRNAME}/${BASENAME/-acw/}"
for ARG in "$@"; do
	if [ "${NEXT}" == "-arch" ]; then
		if [ "${ARG}" == "i386" ]; then
			PROGARGS+=("-m32");
		elif [ "${ARG}" == "x86_64" ]; then
			PROGARGS+=("-m64");
		else
			PROGARGS+=("${NEXT}" "$ARG");
		fi
		unset NEXT
	elif [ "${ARG}" == "-arch" ]; then
		NEXT="${ARG}";
	else
		PROGARGS+=("${ARG}");
	fi
done
exec "${PROGNAME}" "${PROGARGS[@]}";